"""Rename model_name to llm_model

Revision ID: 4746c4d2cfde
Revises: b905aaee6bdd
Create Date: 2025-11-03 00:53:04.185572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4746c4d2cfde'
down_revision: Union[str, None] = 'b905aaee6bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.drop_column('messages', 'model_name')
    op.add_column('projects', sa.Column('default_llm_model', sa.String(length=100), nullable=True))
    op.drop_column('projects', 'default_model')
    op.add_column('sessions', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.drop_column('sessions', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'llm_model')
    op.add_column('projects', sa.Column('default_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('projects', 'default_llm_model')
    op.add_column('messages', sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('messages', 'llm_model')
    # ### end Alembic commands ###
